version: "3.9"

services:
   jira-mcp:
     image: ghcr.io/sooperset/mcp-atlassian:latest
     container_name: jira-mcp
     environment:
       - JIRA_URL="https://yourinstance.atlassian.net"
       - JIRA_USERNAME="jirauser@gmail.com"
       - JIRA_API_TOKEN=""
       - MCP_PORT=8000
     ports:
       - "8000:8000"
     command: "--verbose --transport sse --no-jira-ssl-verify"
     networks:
       - mcp-network

networks:
  mcp-network:
    driver: bridge
